ALTER TABLE members ADD FOREIGN KEY (email) REFERENCES members_info(email) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE members_info ADD FOREIGN KEY (sport_ID) REFERENCES sports(sport_ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE sports ADD FOREIGN KEY (professionalism_ID) REFERENCES professionalisms(professionalism_ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE members_info ADD FOREIGN KEY (role_ID) REFERENCES roles(role_ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE members_info ADD FOREIGN KEY (duration_group_ID) REFERENCES duration_groups(duration_group_ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE members_info ADD FOREIGN KEY (membership_type_ID) REFERENCES memberships(membership_type_ID) ON DELETE CASCADE ON UPDATE CASCADE;